services:
  master-pahere01:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://192.168.10.50:443/
    container_name: master-pahere01
    networks:
      red_web:
        ipv4_address: 192.168.10.70

  worker-pahere01:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master-pahere01
    depends_on:
      - master-pahere01
    deploy:
      replicas: 5
    networks:
      - red_web

networks:
  red_web:
    external: true
